### ISSUE TITLE
extend to other applications

### ISSUE THREAD

**Issue by acornejo** [ksuther/SimulatorBorderKiller#1]
Hi,

I would like to remove the window border of another application. Not sure how this app works (does it look for the app by title? executable path? window class?).

In any case, it would be awesome if you could extend your application so that you can choose (perhaps with a mouse click) which application you want to hide the titlebar from. This way we could use your app with multiple applications, and not just the iOS simulator.

**Comment by ksuther** [comment]
Hiding the titlebar of a window is not at all the same as what this does. That would require an entirely separate approach which wouldn't be appropriate here.
